apiVersion: v1
kind: Pod
metadata:
  name: zbio-sample-googlebookapi
  labels:
    app: zbio-sample-googlebookapi
    owner: zbio
    managed-by: roost
spec:
  containers:
  - name: ui
    image: local-registry:5002/ui:latest
    ports:
    - containerPort: 80
    resources:
      requests: {}
      limits:
        memory: "256Mi"
        cpu: "200m"
  - name: bookapi
    image: local-registry:5002/google_book_api:latest
    ports:
      - containerPort: 9999
    env:
    - name: SERVICE_ADDRESS
      value: zbio-service.zbio:50002
    - name: BROKER_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    resources:
      requests: {}
      limits:
        memory: "256Mi"
        cpu: "200m"
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: googlebookapi
  labels:
    app: zbio-sample-googlebookapi
    owner: zbio
    managed-by: roost
spec:
  type: NodePort
  selector:
    app: zbio-sample-googlebookapi
  ports:
  - name: bookapi-tcp
    port: 9999
    targetPort: 9999
  - name: ui-tcp
    port: 9998
    targetPort: 80
    nodePort: 30045
